### ISSUE TITLE
Content Revisions

### ISSUE THREAD

**Issue by jonush** [bluegoo192/dssite#15]
please update the club meeting times at the bottom of the `home` page and `about` page:

`home`:
Our club meets every Tuesday from 7:00 p.m. to 9:00 p.m. in the [DAHC](https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/30443321_1315605055250038_1466998762189002677_n.png?_nc_cat=0&oh=02d6e935ac5b370825ece13b1d0800b5&oe=5B5305AF). 

`about`:
Drop by one of our meetings to talk to us in person! Our club holds meetings every Tuesday from 7:00 p.m. to 9:00 p.m. in the [DAHC](https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/30443321_1315605055250038_1466998762189002677_n.png?_nc_cat=0&oh=02d6e935ac5b370825ece13b1d0800b5&oe=5B5305AF).

**Comment by jonhsu97** [comment]
please store the image whichever way you best see fit. thanks!
